version: '3.8'

services:
  energi_zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    container_name: energi_zookeeper
    ports:
      - "22181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  energi_kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: energi_kafka
    depends_on:
      - energi_zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: energi_zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://energi_kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # Energi PostgreSQL database
  energi_postgres:
    image: postgres:16
    container_name: energi_postgres
    ports:
      - "55432:5432"              # use a unique port to avoid clash
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: energi_data
    volumes:
      - energi_pgdata:/var/lib/postgresql/data

volumes:
  energi_pgdata:
