apiVersion: v1
kind: Secret
metadata:
  name: energi-postgres-secret
  namespace: bd-bd-gr-07
type: Opaque
data:
  POSTGRES_USER: ZW5lcmdpdXNlcg==       # "energiuser"
  POSTGRES_PASSWORD: ZW5lcmdpcGFzc3dvcmQ= # "energipassword"
  POSTGRES_DB: ZW5lcmdpZGI=             # "energidb"
